version: '3.7'
services:
  test_0:
    container_name: test_0
    build:
      context: ./
      dockerfile: .Dockerfile
      args:
        SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
        BRANCH_NAME: ${BRANCH_NAME}
    stdin_open: true
    ports:
      - 3001:3000