version: '3.7'

services:

  branch-container-sample:
    container_name: branch-container-sample
    build:
      context: ./
      dockerfile: .Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000